<?php

/**
 * Implements hook_migrate_api().
 */

 function curso_migration_migrate_api() {
  $api = array(
    'api' => 2,
    'groups' => array(
      'curso' => array(
        'title' => 'Migraciones del Curso Drupal'
      )
    ),
    'migrations' => array(
      'entradasblog' => array(
        'class_name' => 'EntradasBlogMigration',
        'group_name' => 'curso',
        'dependencies' => array('categoriesblog'),
      ),
      'categoriesblog' => array(
        'class_name' => 'CategoriesBlogMigration',
        'group_name' => 'curso',
      ),
    )
  );

  return $api;
 }

/**
 * Implements hook_menu()
 */
 function curso_migration_menu() {
  $items['blog_legacy_id/%legacy_to_nid'] = array(
    'title' => 'Redirección de legacy ID a nid',
    'page callback' => 'drupal_goto',
    'page arguments' => array(1),
    'access callback' => 'user_is_logged_in'
  );

  return $items;
}

function legacy_to_nid_load($lid) {
  $result = db_select('migrate_map_entradasblog', 'mme')
    ->fields('mme', array('destid1'))
    ->condition('sourceid1', $lid, '=')
    ->execute()
    ->fetchField(0);

  if ($result) {
    return 'node/' . $result;
  }
  return FALSE;
}