<?php

/**
 * Implements hook_menu()
 */
function catalogo_menu() {
  $items['admin/config/catalogo'] = array(
    'title' => 'Gestión de catálogo',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('catalogo_form'),
    'access arguments' => array('administer content'),
    'type' => MENU_CALLBACK
  );

  $items['catalogo'] = array(
    'title' => 'Gestión del catálogo',
    'page callback' => '_catalogo_show_catalogo_full',
    'access arguments' => array('access content'),
  );

  return $items;
}

function catalogo_form($form, &$form_state) {

  $form['config'] = array(
    '#title' => 'Configuración básica',
    '#type' => 'fieldset'
  );

  $form['config']['oferta'] = array(
    '#type' => 'checkbox',
    '#title' => 'Oferta 20%',
    '#default_value' => variable_get('catalogo_oferta', 0)
  );

  $form['config']['desc_corta'] = array(
    '#title' => 'Descripción corta',
    '#type' => 'textfield',
    '#default_value' => variable_get('catalogo_desc_corta', '')
  );

  $form['config']['desc_larga'] = array(
    '#title' => 'Descripción larga',
    '#type' => 'textarea',
    '#default_value' => variable_get('catalogo_desc_larga', '')
  );

  $form['config']['catalogo_pdf'] = array(
    '#title' => 'PDF del catálogo',
    '#type' => 'managed_file',
    '#description' => 'Sube el catálogo en formato PDF',
    '#upload_location' => 'public://catalogos/',
    '#default_value' => variable_get('catalogo_pdf', ''),
    '#upload_validators' => array(
      'file_validate_extensions' => array('pdf'),
    ),
    '#required' => TRUE,
  );

  $form["submit_button"] = array(
    '#type' => 'submit',
    '#value' => 'Guardar'
  );

  return $form;
}

function catalogo_form_validate($form, &$form_state) {
  if (strlen($form_state['values']['desc_corta']) < 5 ) {
    form_set_error('desc_corta', 'La descripción corta debe ser mayor de 5 caracteres');
  }
}

function catalogo_form_submit($form, &$form_state) {
  variable_set('catalogo_desc_corta', $form_state['values']['desc_corta']);
  variable_set('catalogo_desc_larga', $form_state['values']['desc_larga']);
  variable_set('catalogo_oferta', $form_state['values']['oferta']);
  variable_set('catalogo_pdf', $form_state['values']['catalogo_pdf']);
  $file = file_load($form_state['values']['catalogo_pdf']);
  $file->status = FILE_STATUS_PERMANENT;
  file_save($file);
  file_usage_add($file, 'catalogo', 'file', 1);
  drupal_set_message('Las opciones del catálogo se han guardado correctamente');
}

/**
 * Implements hook_block_info().
 */
function catalogo_block_info() {
  // This example comes from node.module.
  $blocks['catalogo'] = array(
    'info' => 'Catálogo',
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function catalogo_block_view($delta) {
  $block = array();
  if ($delta == 'catalogo') {
    $block['subject'] = 'Catálogo';
    $block['content'] = _catalogo_get_info();
  }

  return $block;
}

function _catalogo_get_info() {
  // $content = '';
  // if (variable_get('catalogo_oferta')) {
  //   $content .= '<p>¡Todo nuestro catálogo al 20%!</p>';
  // }
  // $content .= '<p>' . variable_get('catalogo_desc_corta') .'</p>';

  // if($fid = variable_get('catalogo_pdf', 0)) {
  //   $file = file_load($fid);
  //   if ($file) {
  //     $content .= l('Catalogo PDF', file_create_url($file->uri));
  //   }
  // }

  $variables['catalogo_desc_corta'] = variable_get('catalogo_desc_corta');
  $variables['catalogo_oferta'] = variable_get('catalogo_oferta');
  $variables['catalogo_pdf'] = variable_get('pdf');
  return theme('catalogo_bloque', $variables);

}

function _catalogo_show_catalogo_full() {
  $content = '';
  $content .= '<p>' . variable_get('catalogo_desc_larga') . '</p>';
  if (variable_get('catalogo_oferta')) {
    $content .= '<p>Todo nuestro catálogo al 20%!</p>';
  }
  if ($fid = variable_get('catalogo_pdf')) {
    $file = file_load($fid);
    if ($file) {
      $content .= l('Catalogo PDF', $file->uri);
    }
  }
  return $content;
}

/**
 * Implements hook_theme().
 */
function catalogo_theme($existing, $type, $theme, $path) {
  return array(
    'catalogo_bloque' => array(
      'template' => 'catalogo-bloque',
      'variables' => array(
        'catalogo_desc_corta' => NULL,
        'catalogo_oferta' => NULL,
        'catalogo_pdf' => NULL,
      )
    )
  );
}


function template_process_catalogo_bloque(&$variables) {
  if ($variables['catalogo_pdf']) {
    $file = file_load($variables['catalogo_pdf']);
    if ($file) {
      $pdf = l('Catalogo PDF', file_create_url($file->uri));
      $variables['enlace_pdf'] = $pdf;
    }
  }
}